import { Component, OnInit } from '@angular/core';
import { MatCard, MatCardContent } from '@angular/material/card';
import { RouterOutlet } from '@angular/router';
import { ChartComponent } from './components/chart/chart.component';
import { CurrenciesComponent } from './components/currencies/currencies.component';
import { MarketPriceComponent } from './components/market-price/market-price.component';

@Component({
  selector: 'app-root',
  standalone: true,
  imports: [
    RouterOutlet,
    ChartComponent,
    CurrenciesComponent,
    MarketPriceComponent,
    MatCard,
    MatCardContent,
  ],
  templateUrl: './app.component.html',
  styleUrl: './app.component.scss',
})
export class AppComponent implements OnInit {
  title = 'test-fintech';
  private readonly ACCESS_TOKEN =
    'eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJTUDJFWmlsdm8zS2g3aGEtSFRVU0I3bmZ6dERRN21tb3M3TXZndlI5UnZjIn0.eyJleHAiOjE3MTk4Mjk3OTMsImlhdCI6MTcxOTgyNzk5MywiYXV0aF90aW1lIjoxNzE5MTUyOTAxLCJqdGkiOiJhNWUwMDgwNy1lZDY0LTQyMDQtYTM5ZS03MzcyODY0MmUzYzAiLCJpc3MiOiJodHRwczovL3BsYXRmb3JtLmZpbnRhY2hhcnRzLmNvbS9pZGVudGl0eS9yZWFsbXMvZmludGF0ZWNoIiwiYXVkIjpbIm5ld3MtY29uc29saWRhdG9yIiwiYmFycy1jb25zb2xpZGF0b3IiLCJ0cmFkaW5nLWNvbnNvbGlkYXRvciIsImNvcHktdHJhZGVyLWNvbnNvbGlkYXRvciIsInBheW1lbnRzIiwid2ViLXNvY2tldHMtc3RyZWFtaW5nIiwidXNlci1kYXRhLXN0b3JlIiwiYWxlcnRzLWNvbnNvbGlkYXRvciIsInVzZXItcHJvZmlsZSIsImVtYWlsLW5vdGlmaWNhdGlvbnMiLCJpbnN0cnVtZW50cy1jb25zb2xpZGF0b3IiLCJhY2NvdW50Il0sInN1YiI6Ijk1ZTY2ZGJiLTQ3YTctNDhkOS05ZGZlLTRlYzZjZTQxY2I0MSIsInR5cCI6IkJlYXJlciIsImF6cCI6IndlYi1hcHAiLCJub25jZSI6ImQwZThmNGY2LTY4ZTYtNGFjMS05OGFiLWI3MzlmYTk3YTBkNCIsInNlc3Npb25fc3RhdGUiOiJlZjExMTVmOS1kMjkyLTQ3OTAtODY1My01ZDE4YjM1NDM4ZmEiLCJhY3IiOiIwIiwiYWxsb3dlZC1vcmlnaW5zIjpbImh0dHBzOi8vcGxhdGZvcm0uZmludGFjaGFydHMuY29tIiwiaHR0cDovL2xvY2FsaG9zdDo0MjAwIiwiaHR0cHM6Ly9hcHAuZ29zYW5keS5pbyJdLCJyZWFsbV9hY2Nlc3MiOnsicm9sZXMiOlsib2ZmbGluZV9hY2Nlc3MiLCJkZWZhdWx0LXJvbGVzLWZpbnRhdGVjaCIsInVtYV9hdXRob3JpemF0aW9uIiwidXNlcnMiXX0sInJlc291cmNlX2FjY2VzcyI6eyJhY2NvdW50Ijp7InJvbGVzIjpbIm1hbmFnZS1hY2NvdW50IiwibWFuYWdlLWFjY291bnQtbGlua3MiLCJ2aWV3LXByb2ZpbGUiXX19LCJzY29wZSI6Im9wZW5pZCBlbWFpbCBwcm9maWxlIiwic2lkIjoiZWYxMTE1ZjktZDI5Mi00NzkwLTg2NTMtNWQxOGIzNTQzOGZhIiwiZW1haWxfdmVyaWZpZWQiOnRydWUsInJvbGVzIjpbIm9mZmxpbmVfYWNjZXNzIiwiZGVmYXVsdC1yb2xlcy1maW50YXRlY2giLCJ1bWFfYXV0aG9yaXphdGlvbiIsInVzZXJzIl0sIm5hbWUiOiJEZW1vIFVzZXIiLCJwcmVmZXJyZWRfdXNlcm5hbWUiOiJyX3Rlc3RAZmludGF0ZWNoLmNvbSIsImdpdmVuX25hbWUiOiJEZW1vIiwiZmFtaWx5X25hbWUiOiJVc2VyIiwiZW1haWwiOiJyX3Rlc3RAZmludGF0ZWNoLmNvbSJ9.X-toPo27KJ8-OmIl0SoiEyepcxZ-0XRrWaz15cBdPvCixhdZJp_IjM36O0eyeputBnsIAVDQTwY3I72_ViHdIZcSY9q57coMPi0AEERPq7exRN5Gez2qXzPmrXcxgJWUqutAvjqQQguqjJly4H2uJdFkWgcQFBpZP_QtSvhJL9vezWxmNU5Yn6Z5qCG33-sxITOwyugHIhKGNXd-uT_frS1bJBFg-j738B-0DEtCQsNxph0BfExusRNXjEx4d5GwrB77G1e_5qtT_8NbEFQx86QPZPJVwM5rwm0My6PZ1mwMsAM2W5yEvBwOIJqhvUYipATtj2cew5kQe44LbDqj-Q';

  ngOnInit(): void {
    localStorage.setItem('accessToken', this.ACCESS_TOKEN);
  }
}
