import {Component, OnInit} from '@angular/core';
import { RouterOutlet } from '@angular/router';
import {ChartComponent} from "./components/chart/chart.component";
import {CurrenciesComponent} from "./components/currencies/currencies.component";
import {MarketPriceComponent} from "./components/market-price/market-price.component";
import {MatCard, MatCardContent} from "@angular/material/card";

@Component({
  selector: 'app-root',
  standalone: true,
  imports: [RouterOutlet, ChartComponent, CurrenciesComponent, MarketPriceComponent, MatCard, MatCardContent],
  templateUrl: './app.component.html',
  styleUrl: './app.component.scss'
})
export class AppComponent implements OnInit{
  title = 'test-fintech';
  private readonly ACCESS_TOKEN = 'eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJTUDJFWmlsdm8zS2g3aGEtSFRVU0I3bmZ6dERRN21tb3M3TXZndlI5UnZjIn0.eyJleHAiOjE3MTkyMjY0MzEsImlhdCI6MTcxOTIyNDYzMSwiYXV0aF90aW1lIjoxNzE5MTUyOTAxLCJqdGkiOiJkZWZiY2Q0YS02ZmRkLTQ2YjktYmM2Zi03OWFjMDNiZDhmYTMiLCJpc3MiOiJodHRwczovL3BsYXRmb3JtLmZpbnRhY2hhcnRzLmNvbS9pZGVudGl0eS9yZWFsbXMvZmludGF0ZWNoIiwiYXVkIjpbIm5ld3MtY29uc29saWRhdG9yIiwiYmFycy1jb25zb2xpZGF0b3IiLCJ0cmFkaW5nLWNvbnNvbGlkYXRvciIsImNvcHktdHJhZGVyLWNvbnNvbGlkYXRvciIsInBheW1lbnRzIiwid2ViLXNvY2tldHMtc3RyZWFtaW5nIiwidXNlci1kYXRhLXN0b3JlIiwiYWxlcnRzLWNvbnNvbGlkYXRvciIsInVzZXItcHJvZmlsZSIsImVtYWlsLW5vdGlmaWNhdGlvbnMiLCJpbnN0cnVtZW50cy1jb25zb2xpZGF0b3IiLCJhY2NvdW50Il0sInN1YiI6Ijk1ZTY2ZGJiLTQ3YTctNDhkOS05ZGZlLTRlYzZjZTQxY2I0MSIsInR5cCI6IkJlYXJlciIsImF6cCI6IndlYi1hcHAiLCJub25jZSI6IjhlZDllYWUwLWU4ZmQtNDgyMy1iYzRhLWE4OGNiNDc3MDBmOCIsInNlc3Npb25fc3RhdGUiOiJlZjExMTVmOS1kMjkyLTQ3OTAtODY1My01ZDE4YjM1NDM4ZmEiLCJhY3IiOiIwIiwiYWxsb3dlZC1vcmlnaW5zIjpbImh0dHBzOi8vcGxhdGZvcm0uZmludGFjaGFydHMuY29tIiwiaHR0cDovL2xvY2FsaG9zdDo0MjAwIiwiaHR0cHM6Ly9hcHAuZ29zYW5keS5pbyJdLCJyZWFsbV9hY2Nlc3MiOnsicm9sZXMiOlsib2ZmbGluZV9hY2Nlc3MiLCJkZWZhdWx0LXJvbGVzLWZpbnRhdGVjaCIsInVtYV9hdXRob3JpemF0aW9uIiwidXNlcnMiXX0sInJlc291cmNlX2FjY2VzcyI6eyJhY2NvdW50Ijp7InJvbGVzIjpbIm1hbmFnZS1hY2NvdW50IiwibWFuYWdlLWFjY291bnQtbGlua3MiLCJ2aWV3LXByb2ZpbGUiXX19LCJzY29wZSI6Im9wZW5pZCBlbWFpbCBwcm9maWxlIiwic2lkIjoiZWYxMTE1ZjktZDI5Mi00NzkwLTg2NTMtNWQxOGIzNTQzOGZhIiwiZW1haWxfdmVyaWZpZWQiOnRydWUsInJvbGVzIjpbIm9mZmxpbmVfYWNjZXNzIiwiZGVmYXVsdC1yb2xlcy1maW50YXRlY2giLCJ1bWFfYXV0aG9yaXphdGlvbiIsInVzZXJzIl0sIm5hbWUiOiJEZW1vIFVzZXIiLCJwcmVmZXJyZWRfdXNlcm5hbWUiOiJyX3Rlc3RAZmludGF0ZWNoLmNvbSIsImdpdmVuX25hbWUiOiJEZW1vIiwiZmFtaWx5X25hbWUiOiJVc2VyIiwiZW1haWwiOiJyX3Rlc3RAZmludGF0ZWNoLmNvbSJ9.H1UF_KIHxAZra-WvtVEP5iRXJUg4qQ0gNB-PJMJM2VYWTa5rp5Lrz42NJyUsTVDk22_GYqAp1hU2VgEX9OCFTHx9ndGIw3HDEA23zaJN9kcca1rD3611rGk6i8q14lS2mKCouOfEwXid91pkIP1E57RQW_AbMmRNZ_kJ0HGSgRY5SzP-Z-GKIcZSC2BIH2hSZ3PnA7U7YNFg24N_qeYEDXFl8IGGEx4IOw2VIUIRCCBBDuRvXTg-WY1vcFq_nwWVqJ9BV6Ty3YNvS7fJ6x8KYufLdV43KJW2Yb5DllckGTYWOXJJkFsDWGOhXa6539PdaKa0ZE5NQDcEu-VdBc-cMg';

  ngOnInit(): void {
    localStorage.setItem('accessToken', this.ACCESS_TOKEN)
  }
}
