import {Component, OnInit} from '@angular/core';
import { RouterOutlet } from '@angular/router';
import {ChartComponent} from "./components/chart/chart.component";
import {CurrenciesComponent} from "./components/currencies/currencies.component";
import {MarketPriceComponent} from "./components/market-price/market-price.component";
import {MatCard, MatCardContent} from "@angular/material/card";

@Component({
  selector: 'app-root',
  standalone: true,
  imports: [RouterOutlet, ChartComponent, CurrenciesComponent, MarketPriceComponent, MatCard, MatCardContent],
  templateUrl: './app.component.html',
  styleUrl: './app.component.scss'
})
export class AppComponent implements OnInit{
  title = 'test-fintech';
  private readonly ACCESS_TOKEN = 'eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJTUDJFWmlsdm8zS2g3aGEtSFRVU0I3bmZ6dERRN21tb3M3TXZndlI5UnZjIn0.eyJleHAiOjE3MTkxOTA2MTYsImlhdCI6MTcxOTE4ODgxNiwiYXV0aF90aW1lIjoxNzE5MTUyOTAxLCJqdGkiOiIzMzUzNWRkOC0yNjkwLTRhYzktYjY3ZS1jNmM5NmE5ZTEzMDEiLCJpc3MiOiJodHRwczovL3BsYXRmb3JtLmZpbnRhY2hhcnRzLmNvbS9pZGVudGl0eS9yZWFsbXMvZmludGF0ZWNoIiwiYXVkIjpbIm5ld3MtY29uc29saWRhdG9yIiwiYmFycy1jb25zb2xpZGF0b3IiLCJ0cmFkaW5nLWNvbnNvbGlkYXRvciIsImNvcHktdHJhZGVyLWNvbnNvbGlkYXRvciIsInBheW1lbnRzIiwid2ViLXNvY2tldHMtc3RyZWFtaW5nIiwidXNlci1kYXRhLXN0b3JlIiwiYWxlcnRzLWNvbnNvbGlkYXRvciIsInVzZXItcHJvZmlsZSIsImVtYWlsLW5vdGlmaWNhdGlvbnMiLCJpbnN0cnVtZW50cy1jb25zb2xpZGF0b3IiLCJhY2NvdW50Il0sInN1YiI6Ijk1ZTY2ZGJiLTQ3YTctNDhkOS05ZGZlLTRlYzZjZTQxY2I0MSIsInR5cCI6IkJlYXJlciIsImF6cCI6IndlYi1hcHAiLCJub25jZSI6IjkzYWMzZTk4LTI3YWYtNDNiZS04NjY4LThlODQzNDYxMTUzMiIsInNlc3Npb25fc3RhdGUiOiJlZjExMTVmOS1kMjkyLTQ3OTAtODY1My01ZDE4YjM1NDM4ZmEiLCJhY3IiOiIwIiwiYWxsb3dlZC1vcmlnaW5zIjpbImh0dHBzOi8vcGxhdGZvcm0uZmludGFjaGFydHMuY29tIiwiaHR0cDovL2xvY2FsaG9zdDo0MjAwIiwiaHR0cHM6Ly9hcHAuZ29zYW5keS5pbyJdLCJyZWFsbV9hY2Nlc3MiOnsicm9sZXMiOlsib2ZmbGluZV9hY2Nlc3MiLCJkZWZhdWx0LXJvbGVzLWZpbnRhdGVjaCIsInVtYV9hdXRob3JpemF0aW9uIiwidXNlcnMiXX0sInJlc291cmNlX2FjY2VzcyI6eyJhY2NvdW50Ijp7InJvbGVzIjpbIm1hbmFnZS1hY2NvdW50IiwibWFuYWdlLWFjY291bnQtbGlua3MiLCJ2aWV3LXByb2ZpbGUiXX19LCJzY29wZSI6Im9wZW5pZCBlbWFpbCBwcm9maWxlIiwic2lkIjoiZWYxMTE1ZjktZDI5Mi00NzkwLTg2NTMtNWQxOGIzNTQzOGZhIiwiZW1haWxfdmVyaWZpZWQiOnRydWUsInJvbGVzIjpbIm9mZmxpbmVfYWNjZXNzIiwiZGVmYXVsdC1yb2xlcy1maW50YXRlY2giLCJ1bWFfYXV0aG9yaXphdGlvbiIsInVzZXJzIl0sIm5hbWUiOiJEZW1vIFVzZXIiLCJwcmVmZXJyZWRfdXNlcm5hbWUiOiJyX3Rlc3RAZmludGF0ZWNoLmNvbSIsImdpdmVuX25hbWUiOiJEZW1vIiwiZmFtaWx5X25hbWUiOiJVc2VyIiwiZW1haWwiOiJyX3Rlc3RAZmludGF0ZWNoLmNvbSJ9.onjOZLvYaoJXWRjPaGwcV1yzQ-LXEae2hK0kcxQpjbGpwcVNi8AZcP4wnwdV4ti1VNYRTtvbQDhevXZB4U0JVy3YBa7SVA0-p_Zgi6yRIkfjJVKLimKI0GovWAPvZVUuQAQxotzMrPgJyd5YCpbjKVnwdZ0qJKyQC-SLN_yaqP6cpDQMXtcxfgeqZKLQoX66QZGoOThy6QlQuBpXoKDIxjcYsL5Vptvxfu_5KMT_ASVW6axJFhADxJqGHGFajWFSru7zHgKdPKIix0XTXJIro5pnfTDSCKqi3Fh3mNF-Q57VJMASpjb76H2t8vm5QSgCzZM-LXHEQbUqbOpn-NaNIQ';

  ngOnInit(): void {
    localStorage.setItem('accessToken', this.ACCESS_TOKEN)
  }
}
